# Generated by Django 3.2.6 on 2021-11-06 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('category', models.CharField(max_length=255, verbose_name='Тема')),
                ('news_link', models.CharField(max_length=255, verbose_name='Ссылка на статью')),
                ('post_time', models.CharField(max_length=255, verbose_name='Время выкладывания')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_box', models.CharField(max_length=255, null=True, verbose_name='Почта пользователя')),
                ('favourite_articles', models.ManyToManyField(blank=True, related_name='favourite_articles', to='news_show.FavouriteArticle')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
        ),
        migrations.AddField(
            model_name='favouritearticle',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_show.newsarticle', verbose_name='Избранная новость'),
        ),
        migrations.AddField(
            model_name='favouritearticle',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_show.reader', verbose_name='Читатель'),
        ),
    ]
