# Generated by Django 3.2.6 on 2021-11-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_show', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='name',
            new_name='user',
        ),
    ]
